In [85]:
import requests
from bs4 import BeautifulSoup

from selenium import webdriver 
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from selenium.common.exceptions import NoSuchElementException, ElementNotInteractableException
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

import pandas as pd
from time import sleep

In [86]:
driver_path = Service(r"C:\Users\Lenovo\Desktop\chromedriver.exe")
driver = webdriver.Chrome(service=driver_path)
driver.get('https://store.unionlosangeles.com/collections/outerwear')

brands = []
df = pd.DataFrame(columns=['brand', 'title', 'price', 'image'])


while True:
    for i in range(1, 31):
        try:
            sleep(3)
            title_path = '//*[@id="isp_search_results_container"]/li[' + str(i) + ']/div[2]/div[4]'
            title = driver.find_element(By.XPATH, title_path).text

            brand_path = '//*[@id="isp_search_results_container"]/li[' + str(i) + ']/div[2]/div[3]'
            brand = driver.find_element(By.XPATH, brand_path).text

            price_path = '//*[@id="isp_search_results_container"]/li[' + str(i) + ']/div[2]/div[5]/span'
            price = driver.find_element(By.XPATH, price_path).text

            sleep(1)
            img_path = '//*[@id="isp_search_results_container"]/li[' + str(i) + ']/div[1]/a/img'
            img = driver.find_element(By.CLASS_NAME, 'isp_product_image').get_attribute('src')

            #df = df.append({'brand':brand, 'title':title, 'price':price, 'image':img}, ignore_index=True)
            new_index = len(df)
            df.loc[new_index] = [brand, title, price, img]
        except NoSuchElementException:
            pass
    
    sleep(3)
    try:
        next_path = '//*[@id="isp_pagination_anchor"]/ul/li[8]/a'    
        next_page = driver.find_element(By.XPATH, next_path)
        next_page.send_keys(Keys.ENTER)
    except ElementNotInteractableException:
        print('DONE')
        break

DONE

In [90]:
df

,brand,title,price,image
0,KAPITAL,60/40 CLOTH BUG ANORAK (1TONE),$747.00,https://cdn.shopify.com/s/files/1/0051/0392/pr...
1,KAPITAL,SKA-LINE JAM TRACK JACKET,$423.00,https://cdn.shopify.com/s/files/1/0051/0392/pr...
2,OFF-WHITE,NEEN HARRINGTON,$2265.00,https://cdn.shopify.com/s/files/1/0051/0392/pr...
3,KAPITAL,60/40 CLOTH BUG ANORAK (1TONE),$747.00,https://cdn.shopify.com/s/files/1/0051/0392/pr...
4,KAPITAL,SMOOTH JERSEY STAND MAN & WOMAN TRACK JKT,$423.00,https://cdn.shopify.com/s/files/1/0051/0392/pr...
...,...,...,...,...
157,VISVIM,SS 101 JKT DRY DMGD,$2200,https://cdn.shopify.com/s/files/1/0051/0392/pr...
158,COMME DES GARÇONS SHIRT,FUTURA EDITION BLOUSON,$1110,https://cdn.shopify.com/s/files/1/0051/0392/pr...
159,TOGA VIRILIS,RAYON WESTERN BLOUSON,$913,https://cdn.shopify.com/s/files/1/0051/0392/pr...
160,VISVIM,SS 101 JKT DRY DMGD-1000,$1887,https://cdn.shopify.com/s/files/1/0051/0392/pr...
161,COMME DES GARÇONS HOMME PLUS,DECONSTRUCTED WOOL BLAZER,$1378,https://cdn.shopify.com/s/files/1/0051/0392/pr...

Convert the price column into float

In [91]:
def dollar(entry):
    entry = entry.replace('$', '')
    return float(entry)

In [92]:
df.price = df.price.apply(lambda x: dollar(x))
df.head()

,brand,title,price,image
0,KAPITAL,60/40 CLOTH BUG ANORAK (1TONE),747.0,https://cdn.shopify.com/s/files/1/0051/0392/pr...
1,KAPITAL,SKA-LINE JAM TRACK JACKET,423.0,https://cdn.shopify.com/s/files/1/0051/0392/pr...
2,OFF-WHITE,NEEN HARRINGTON,2265.0,https://cdn.shopify.com/s/files/1/0051/0392/pr...
3,KAPITAL,60/40 CLOTH BUG ANORAK (1TONE),747.0,https://cdn.shopify.com/s/files/1/0051/0392/pr...
4,KAPITAL,SMOOTH JERSEY STAND MAN & WOMAN TRACK JKT,423.0,https://cdn.shopify.com/s/files/1/0051/0392/pr...

In [99]:
df.image[0]

'https://cdn.shopify.com/s/files/1/0051/0392/products/067122_Kapitalflats043_600x.jpg?v=1655426715'

Display top ten most expensive products

In [98]:
df.sort_values(by='price', ascending=False).head(10)

,brand,title,price,image
98,RAF SIMONS,DOUBLE-FACED STERLING COAT WITH PATCHES,5578.0,https://cdn.shopify.com/s/files/1/0051/0392/pr...
86,VISVIM,KRUPA FIELD DOWN JACKET,5316.0,https://cdn.shopify.com/s/files/1/0051/0392/pr...
44,VISVIM,ALTA FIELD DOWN JACKET (NY/C),3875.0,https://cdn.shopify.com/s/files/1/0051/0392/pr...
120,VISVIM,HARRIER DOWN JACKET,3718.0,https://cdn.shopify.com/s/files/1/0051/0392/pr...
113,VISVIM,THORSON II BOMBER JACKET,3260.0,https://cdn.shopify.com/s/files/1/0051/0392/pr...
36,OFF-WHITE,METEOR BLAZER,3235.0,https://cdn.shopify.com/s/files/1/0051/0392/pr...
20,VISVIM,LEVINSON FISHTAIL,3020.0,https://cdn.shopify.com/s/files/1/0051/0392/pr...
62,VISVIM,HARRIER DOWN VEST,2860.0,https://cdn.shopify.com/s/files/1/0051/0392/pr...
30,VISVIM,LAKOTA PARKA,2431.0,https://cdn.shopify.com/s/files/1/0051/0392/pr...
2,OFF-WHITE,NEEN HARRINGTON,2265.0,https://cdn.shopify.com/s/files/1/0051/0392/pr...

In [94]:
df.price.describe()

count     162.000000
mean     1065.740741
std       891.013524
min       120.000000
25%       428.250000
50%       841.000000
75%      1503.500000
max      5578.000000
Name: price, dtype: float64

Get the names of the brands

In [95]:
df.brand.unique()

array(['KAPITAL', 'OFF-WHITE', 'WTAPS', 'INSATIABLE HIGH',
       'COMME DES GARÇONS SHIRT', 'RHUDE', 'COMME DES GARÇONS HOMME PLUS',
       'NIKE', 'SECOND/LAYER', 'OAMC', 'ACRONYM', 'RAF SIMONS', 'VISVIM',
       'THE BREAKS', 'ESSENTIALS', 'AWAKE NY', 'UNION LOS ANGELES',
       'NICHOLAS DALEY', 'A-COLD-WALL*', 'MARTINE ROSE', 'GOODFIGHT',
       'MARNI', 'ADIDAS', 'NEIGHBORHOOD', 'BODE', 'UNUSED',
       'JOHN ELLIOTT', 'WARAIRE BOSWELL', 'BTFL', 'JIL SANDER',
       'EMOTIONALLY UNAVAILABLE', 'PATTA', 'FEAR OF GOD', 'REAL BAD MAN',
       'DICKIES', 'BROWNSTONE', 'CHERRY LOS ANGELES', 'DIVINITIES',
       'LISA LE STRANGE', 'MIHARA YASUHIRO', 'AFIELD OUT', 'TOGA VIRILIS'],
      dtype=object)

Find the number of products per brand

In [96]:
df[['brand', 'title']].groupby('brand').count().sort_values(by='title', ascending=False)

                              title
brand
VISVIM                           20
WTAPS                            14
KAPITAL                          14
NEIGHBORHOOD                      8
NIKE                              7
ACRONYM                           7
JIL SANDER                        6
OAMC                              6
MARNI                             6
BODE                              5
NICHOLAS DALEY                    5
SECOND/LAYER                      4
RAF SIMONS                        4
COMME DES GARÇONS SHIRT           4
OFF-WHITE                         3
MIHARA YASUHIRO                   3
A-COLD-WALL*                      3
COMME DES GARÇONS HOMME PLUS      3
ADIDAS                            3
DICKIES                           3
CHERRY LOS ANGELES                2
RHUDE                             2
REAL BAD MAN                      2
AWAKE NY                          2
PATTA                             2
GOODFIGHT                         2
BROWNSTONE                        2
DIVINITIES                        2
MARTINE ROSE                      2
FEAR OF GOD                       2
WARAIRE BOSWELL                   2
TOGA VIRILIS                      2
THE BREAKS                        1
UNION LOS ANGELES                 1
UNUSED                            1
INSATIABLE HIGH                   1
AFIELD OUT                        1
BTFL                              1
EMOTIONALLY UNAVAILABLE           1
ESSENTIALS                        1
JOHN ELLIOTT                      1
LISA LE STRANGE                   1